### ISSUE TITLE
Can you share the sandpaint package?

### ISSUE THREAD

**Issue by kylestew** [inconvergent/snek#2]
Excited to try out the examples and build some of my own but I'm unable to eve run them. Is it possible I have common lisp mis-installed?

```
 ==== quicklisp quickstart 2015-01-28 loaded ====

    To continue with installation, evaluate: (quicklisp-quickstart:install)

    For installation options, evaluate: (quicklisp-quickstart:help)

unhandled SB-C:COMPILER-ERROR:
  READ error during COMPILE-FILE:

    Package SANDPAINT does not exist.

      Line: 15, Column: 29, File-Position: 275

      Stream: #<SB-SYS:FD-STREAM
                for "file [path replaced]/snek/ex-lines.lisp"
                {11AE6B99}>
```

**Comment by inconvergent** [comment]
i just tried running this version on my installation of sbcl. it works here. i have not other suggestions. the sandpaint package is included in the repo under `src/sandpaint.lisp` and it is loaded via the `src/load.lisp`. 

maybe try running it via sbcl.

**Comment by bhive01** [comment]
I had all kinds of issues until I used SBCL. I started with Clozure CL and it was similarly unable to get anything to run (however, not the same error exactly). From the text above, have you actually installed quicklisp? 
Once I installed SBCL and quicklisp, everything ran without issue. Thanks to @inconvergent for sharing. I wasn't able to me my pictures nearly as pretty, but it was nice to see what lisp looks like and play with the inputs. 👍

**Comment by kylestew** [comment]
Thanks so much for the replies, they put me on the right track.

1) Quicklisp was improperly installed, restarted the install and followed the directions on their website very closely.
2) I misunderstood where the Quicklisp reference needed to be set. It only needs to be entered once in the `src/load.lisp` file. I was replacing the src/load reference in all files, which is obviously wrong :)

The demos are working now. I'm looking forward to coding up some ideas of my own, this is a really different way to look at generative art.

**Comment by inconvergent** [comment]
glad you worked it out.
